In [1]:
# Viewing the data set we have
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.randint(1, 100, size=(20, 10)),
    columns=["Age","Score","Height","Weight","Math","Physics","Chem","Bio","Eng","CS"]
)

print(df) 

    Age  Score  Height  Weight  Math  Physics  Chem  Bio  Eng  CS
0    23     13      95      49    81       42    41   33   70  28
1    11     11      85      70    15       27    29    4   34  24
2    22     10      13      85    90       43    32   12   80  87
3     3     59      93      22    19       55    61    7   17  61
4    37     67      52      92     1       38     2   47   19  57
5    54     61      33      79    61       93    87   95   86  65
6    35     94      21      37    22       46    91   73   93  31
7     4     79      33      89    31       21    48   14   43  87
8    27     48      27      39    30       50    82   59   79  85
9     7     73      21      16    50       10    79   10   39  99
10   55      6      83      81    67       18    65   50   35  72
11   63     40      57      37    51       67    12   55   54  11
12   53     35      13      23    77       12    97   86    3   5
13   49      9      97      58    41       44    96   36   66  35
14   99   

In [ ]:
'''The functions we use to view the dataset '''

# head :show the first given row by default 5  
df.head() # or df.head(10)
# tail : shows the last given row by default 5 
df.tail() # or df.tail(9) last 9 rows 
# sample(): return random rows by default 5 
df.sample()
# shape: shows at the no of row and columns 
df.shape
# columns : the name of columns we have 
df.columns
# index : shows as the rows label
df.index 
# dtypes: type of each columns 
df.dtypes
# info() : this can be very help full for columns name , non-null values, data types and memory usage
df.info() 
#describe(): works for numeric values and calculates count , mean , standard devation , minimum , quartiles , maximum
df.describe()
# .unique(): return all different values in a columns  
df["Age"].unique()
# .nunique() : return number of unique values in each columns
df.nunique()
# value_counts(): count the occurrance of each value in a given columns
df["Age"].value_counts()
# values : return the given dataframe to numpy array just the raw data by removing the index and the columns 
print(df.values) # or the same functionality using the "df.to_numpy()"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      20 non-null     int32
 1   Score    20 non-null     int32
 2   Height   20 non-null     int32
 3   Weight   20 non-null     int32
 4   Math     20 non-null     int32
 5   Physics  20 non-null     int32
 6   Chem     20 non-null     int32
 7   Bio      20 non-null     int32
 8   Eng      20 non-null     int32
 9   CS       20 non-null     int32
dtypes: int32(10)
memory usage: 932.0 bytes
[[23 13 95 49 81 42 41 33 70 28]
 [11 11 85 70 15 27 29  4 34 24]
 [22 10 13 85 90 43 32 12 80 87]
 [ 3 59 93 22 19 55 61  7 17 61]
 [37 67 52 92  1 38  2 47 19 57]
 [54 61 33 79 61 93 87 95 86 65]
 [35 94 21 37 22 46 91 73 93 31]
 [ 4 79 33 89 31 21 48 14 43 87]
 [27 48 27 39 30 50 82 59 79 85]
 [ 7 73 21 16 50 10 79 10 39 99]
 [55  6 83 81 67 18 65 50 35 72]
 [63 40 57 37 51 67 12 55 54 11]
 [53 35 13 23 77 12 97 86